export interface GitHubRepoResult {
  repoName: string;
  repoUrl: string;
  isNew: boolean;
}

export async function createOrGetGitHubRepo(
  owner: string,
  repoName: string,
  token: string
): Promise<GitHubRepoResult> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'Linkal-Website-Builder',
    'X-GitHub-Api-Version': '2022-11-28',
  };

  // 1. Check if repo already exists
  const checkRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, {
    headers,
  });

  if (checkRes.status === 200) {
    const data = await checkRes.json();
    return {
      repoName: data.name,
      repoUrl: data.html_url,
      isNew: false,
    };
  }

  // 2. If not found, create new repo under user
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      ...headers,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      description: `Pure static site generated by Linkal Website Builder`,
      private: false,
      auto_init: true,
    }),
  });

  if (!createRes.ok) {
    const errData = await createRes.json().catch(() => ({}));
    throw new Error(
      `GitHub repo creation failed (${createRes.status}): ${errData.message || createRes.statusText}`
    );
  }

  const newRepo = await createRes.json();
  return {
    repoName: newRepo.name,
    repoUrl: newRepo.html_url,
    isNew: true,
  };
}

export async function commitFileToGitHub(
  owner: string,
  repoName: string,
  filePath: string,
  fileContent: string,
  commitMessage: string,
  token: string
): Promise<{ commitSha: string }> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'Linkal-Website-Builder',
    'X-GitHub-Api-Version': '2022-11-28',
  };

  // 1. Check if file exists to get existing SHA for updating
  let existingSha: string | undefined;
  const getFileRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/contents/${filePath}`,
    { headers }
  );

  if (getFileRes.status === 200) {
    const fileData = await getFileRes.json();
    existingSha = fileData.sha;
  }

  // 2. Put file content (base64 encoded)
  const base64Content = Buffer.from(fileContent, 'utf-8').toString('base64');
  const putRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/contents/${filePath}`,
    {
      method: 'PUT',
      headers: {
        ...headers,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: commitMessage,
        content: base64Content,
        sha: existingSha,
      }),
    }
  );

  if (!putRes.ok) {
    const errData = await putRes.json().catch(() => ({}));
    throw new Error(
      `Failed to commit ${filePath} to GitHub (${putRes.status}): ${errData.message || putRes.statusText}`
    );
  }

  const commitData = await putRes.json();
  return { commitSha: commitData.commit?.sha || 'committed' };
}
